api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    # The list of enabled formats. The first one will be the default.
    formats:
        json:
            mime_types: ['application/json']